apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fah.fullname" . }}
  labels:
{{ include "fah.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fah.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
     {{- with .Values.app.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
     {{- end }} 
      labels:
        app.kubernetes.io/name: {{ include "fah.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: conf
          configMap:
            name: fah
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: conf
            mountPath: /conf
          ports:
            - name: http
              containerPort:  {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.app.healthPath }}
              port:  {{ .Values.app.healthPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.healthPath }}
              port: {{ .Values.app.healthPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
